all:

sync:
	rsync -a orig reduced beagle.henlab.org:/data/public_http/public/cellpile/test/

chromsize:
	cut -f1,2 /big/anbjork/atac_pbmcs/refdata-cellranger-arc-GRCh38-2020-A/fasta/genome.fa.fai > sizes.chromosome

